default:
  type: 'postgres'
  host: '$HOST'
  port: '$POSTGRES_PORT'
  username: '$DB_USER'
  password: '$POSTGRES_PASSWORD'
  database: '$POSTGRES_DB'
test:
  type: 'postgres'
  host: '$HOST_TEST'
  port: '$POSTGRES_TEST_PORT'
  username: '$POSTGRES_TEST_USERNAME'
  password: '$POSTGRES_TEST_PASSWORD'
  database: '$POSTGRES_TEST_DB'
